debug: true
server.port: 8888
spring.application.name: cloud_server

spring.cloud.config.server.git:
  uri: https://github.com/AndresPerezGlobant/CloudConfigProject/
  repos:
    cloud_client:
      uri: https://github.com/AndresPerezGlobant/CloudConfigProject/
      searchPaths:
        - '/cloud_client'
        - '/cloud_client/dev'
        - '/cloud_client/qa'
        - '/cloud_client/prod'
      pattern:
        - '*/*dev*'
        - '*/*qa*'
        - '*/*prod*'