debug: true
server.port: 8888
spring.application.name: cloud_server

spring.cloud.config.server.git:
  uri: /srv/git/crewconfigrepository
  cloneOnStart: true
  repos:
    cloud_client:
      uri: /srv/git/crewconfigrepository
      searchPaths:
        - '/cloud_client'
        - '/cloud_client/dev'
        - '/cloud_client/qa'
        - '/cloud_client/prod'
      pattern:
        - '*/*dev*'
        - '*/*qa*'
        - '*/*prod*'