/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import cloudapp.ConfigServiceApplication;
import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        ConfigServiceApplication classUnderTest = new ConfigServiceApplication();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
